spring:
  application:
    name: multitenancy

  datasource:
    url: jdbc:postgresql://localhost:5432/multitenant
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  flyway:
    create-schemas: false
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration/tenant


server:
  port: 8088
