spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: tenants-route
          uri: http://localhost:8088
          predicates:
            - Host=*.shop
            - Path=/my-shop/**
          filters:
            - name: TenantHeaderFilter

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 80
